import * as actions from './action';

export type DocumentContext = {
  /**
   * The root node of the subtree of the DOM that is potentially editable.
   */
  root: HTMLElement;
  /**
   * The document of the root.  This is a convenience, because we can calculate
   * it at any time.
   */
  document: Document;
  /**
   * The focused element (may be none).  Should not be a TOKEN .
   */
  active: HTMLElement | null;
  /**
   * The currently selected TOKEN (may be none).
   */
  activeToken: HTMLElement | null;
  /**
   * Handles showCurrentSiblings.
   */
  SIB_HIGHLIGHT: Set<HTMLElement>;
  /**
   * Tracks which elements had tabIndex="0" added to them to make them
   * focusable.  Note that some elements may be focusable anyway.
   *
   * This allows for tab navigation of elements in the document.
   */
  TABS: Set<HTMLElement>;
  /**
   * Track which elements have been tokenized.  Such elements must have text
   * nodes as direct descendents.
   */
  tokenized: WeakMap<HTMLElement, boolean>;
  actions: typeof actions;
  listeners: {
    /**
     * Register a listener for FOCUS events.  Consumer can decide if the FOCUS event should occur.
     */
    FOCUS: null | ((evt: JsedFocusEvent) => boolean);
    /**
     * Register a listener for TOKEN_FOCUS events.  Consumer can decide if the TOKEN_FOCUS event should occur.
     */
    TOKEN_FOCUS: null | ((evt: JsedTokenFocusEvent) => boolean);
  };
  unload: () => void;
};

/**
 * Events that are emitted due to navigation and selection of elements within the document.
 */
export type JsedTokenFocusEvent = {
  type: 'FOCUS';
  targetType: 'TOKEN';
  parent: HTMLElement | null;
  value: string;
  /**
   * Request a cursor for the current token.
   */
  requestCursor: () => JsedCursor;
};

export type JsedFocusEvent = {
  type: 'FOCUS';
  targetType: 'F_ELEM';
  /**
   * Lets consumer programmatically move the FOCUS.
   *
   * This navigates the structure of the document.  To navigate words, see requestCursor.
   */
  // requestFocus: () => JsedFocus;
};

export type JsedCursor = {
  /**
   * A way to notify the consumer whenever the cursor (eg the token it points to) changes.
   */
  onChange: (evt: JsedCursorEvent) => void;
  /**
   * Move to previous token if it exists.
   */
  movePrevious: () => void;
  /**
   * Move to next token if it exists.
   */
  moveNext: () => void;
  /**
   * Replace the value of the current token with a new value.
   */
  replace: () => void;
  /**
   * Delete the current token.
   */
  delete: () => void; // go back to previous word or next if no previous
  /**
   * Append a new token after the current one.
   */
  append: () => void;
  /**
   * Prepend a new token after the current one.
   */
  prepend: () => void;
  /**
   * Tell the consumer of events it might wish to heed and close the current edit session.
   */
  // onInterrupt: (evt) => void;
  /**
   * Close the current edit session.
   */
  close: () => void;
};

/**
 * Events generated by a JsedCursor instance.
 */
export type JsedCursorEvent = {
  type: 'CHANGE';
  value: string;
};

export function makeDocumentContext(root: HTMLElement): DocumentContext {
  const documentContext: DocumentContext = {
    root,
    get document(): Document {
      return root.ownerDocument;
    },
    active: null,
    activeToken: null,
    SIB_HIGHLIGHT: new Set(),
    TABS: new Set(),
    tokenized: new WeakMap(),
    actions,
    listeners: {
      FOCUS: null,
      TOKEN_FOCUS: null,
    },
    unload: () => {
      // Placeholder, see below.
      return;
    },
  };
  return documentContext;
}
