/**
 * What can be edited and focused on.
 */

import { JSED_DOM_ROOT_ID, JSED_IGNORE_CLASS } from './constants';
import { isToken } from './token';

const FORM_FOCUSABLE = [
  'input',
  'select',
  'textarea',
  'button',
  'optgroup',
  'option',
  'fieldset',
  'label',
];

/**
 * Elements which are already focusable before we initialize the document either
 * because the document specified it with tabindex or because the elements are
 * innately focusable.  We don't want to mess with the browser tab focus
 * settings on these.
 *
 */
export function isAlreadyFocusable(el: Element): boolean {
  if (FORM_FOCUSABLE.indexOf(el.tagName.toLowerCase()) !== -1) {
    return true;
  }
  if (
    el.hasAttribute('contenteditable') &&
    el.getAttribute('contenteditable') === 'true'
  ) {
    return true;
  }
  if (el.getAttribute('tabindex')) {
    return true;
  }
  return false;
}

/**
 * Governs which elements actions like REC_NEXT can land on but not recurse into.
 *
 * This can be used to focus on things that may require special treatment such
 * as a katex element that has been generated by katex.
 */
export function ignoreDescendents(
  el: Element | Node | null | undefined,
): boolean {
  if (el instanceof Element) {
    if (el.classList.contains('katex')) {
      return true;
    }
    if (el.id === JSED_DOM_ROOT_ID) {
      return true;
    }
  }
  return false;
}

export function isIgnorable(el: Element): boolean {
  if (el.classList.contains(JSED_IGNORE_CLASS)) {
    return true;
  }
  return false;
}

/**
 * Governs which elements actions like REC_NEXT should traverse.  This tests for F_ELEM .
 */
export function isFocusable(
  el: EventTarget | Element | null | undefined,
): el is HTMLElement {
  if (el instanceof window.HTMLScriptElement) {
    return false;
  }
  const isHTMLElement = el instanceof window.HTMLElement;
  if (isHTMLElement) {
    if (el?.id === JSED_DOM_ROOT_ID) {
      return false;
    }
    // Tokens (text) get a cursor and are not treated as focusable.
    if (isToken(el)) {
      return false;
    }
    if (isIgnorable(el)) {
      return false;
    }
  }
  return isHTMLElement;
}
