/**
 * What can be edited and focused on.
 */

const FORM_FOCUSABLE = [
  'input',
  'select',
  'textarea',
  'button',
  'optgroup',
  'option',
  'fieldset',
  'label',
];

/**
 * Elements which are already focusable before we initialize the document either
 * because the document specified it with tabindex or because the elements are
 * innately focusable.  We don't want to mess with the browser tab focus
 * settings on these.
 *
 * TABS is assumed to track elements that were manually made focusable by us
 * because they were not "already-focusable".
 */
export function isAlreadyFocusable(
  TABS: Set<HTMLElement>,
  el: Element,
): boolean {
  if (el instanceof window.HTMLElement && TABS.has(el)) {
    return false;
  }
  if ((el.hasAttribute('tabindex') && el.getAttribute('tabindex')) ?? -2 >= 0) {
    return true;
  }
  if (FORM_FOCUSABLE.indexOf(el.tagName.toLowerCase()) !== -1) {
    return true;
  }
  if (
    el.hasAttribute('contenteditable') &&
    el.getAttribute('contenteditable') === 'true'
  ) {
    return true;
  }
  if (el.hasAttribute('tabindex') && el.getAttribute('tabindex') === '-1') {
    return true;
  }
  return false;
}

/**
 * Governs which elements actions like REC_NEXT can land on but not recurse into.
 *
 * This can be used to focus on things that may require special treatment such
 * as a katex element that has been generated by katex.
 */
export function ignoreDescendents(el: Element | null | undefined): boolean {
  if (el?.classList.contains('katex')) {
    return true;
  }
  return false;
}

/**
 * Governs which elements actions like REC_NEXT should traverse.
 */
export function isFocusable(
  el: EventTarget | Element | null | undefined,
): el is HTMLElement {
  if (el instanceof window.HTMLScriptElement) {
    return false;
  }
  const isHTMLElement = el instanceof window.HTMLElement;
  return isHTMLElement;
}
