services:
  app:
    build:
      context: .
      target: development
    ports:
      - "5173:5173"
      - "4173:4173"
      - "9323:9323"
    volumes:
      - .:/app
      # Create an anonymous volumes. This prevents the host's from overwriting
      # the container's `node_modules`.
      - /app/node_modules
      - /app/.svelte-kit
      - /app/.build
      - /app/dist
    environment:
      - NODE_ENV=development
