# https://taskfile.dev

version: '3'

vars:
  # Where oneput lives so we can get the oneput-defaults.css file .
  ONEPUT_DIR: ../oneput
  # Where the oneput default css file lives.
  # We will use this for now and extend it in a separate file we load after.
  ONEPUT_CSS_FILE: src/lib/jsed/styles/oneput-defaults.css

tasks:
  install:
    cmds:
      - rm -rf node_modules
      - pnpm i
  test:
    desc: |
      Run unit tests; but avoid triggering browser tests.
      See vite.config.js
    summary: |
      task test -- --testPathPattern=token
      task test -- -t "test name filter"
    cmds:
      - pnpm run test {{.CLI_ARGS}}
  test:update:
    desc: Update snapshots
    cmds:
      - pnpm run test:update
  fix:
    desc: format + eslint (fix) + check types (no fix)
    cmds:
      - task: format
      - task: eslint:fix
      - task: check
  format:
    desc: format files
    cmds:
      - pnpm run format
  eslint:fix:
    desc: run eslint fixes
    cmds:
      - ./node_modules/.bin/eslint . --fix
  eslint:
    desc: run eslint
    cmds:
      - ./node_modules/.bin/eslint .
  check:
    desc: check types
    cmds:
      - pnpm run check
  check:watch:
    desc: check types
    cmds:
      - pnpm run check --watch
  build:
    desc: build to dist/
    cmds:
      - pnpm run build
