/**
 * Identifiers for jsed editor actions and menu actions (aka commands).
 *
 * The `JSED__` prefix keeps these distinct from Oneput's core actions
 * (`ONEPUT__`) and from a consumer's own actions when their action maps are
 * merged.
 */
export const JsedCommand = {
  /**
   * Cancel out of a operation that is handled by a whole AppObject
   * Eg cancel out of PasteElementUI .
   */
  CANCEL_VIA_EXIT: 'JSED__CANCEL_VIA_EXIT',
  EXIT_EDITOR: 'JSED__EXIT_EDITOR',
  SOFT_EXIT: 'JSED__SOFT_EXIT',
  STOP_EDITING: 'JSED__STOP_EDITING',
  TOGGLE_SELECT: 'JSED__TOGGLE_SELECT',
  // navigation
  DOWN: 'JSED__DOWN',
  UP: 'JSED__UP',
  NEXT: 'JSED__NEXT',
  PREVIOUS: 'JSED__PREVIOUS',
  RIGHT_ARROW: 'JSED__RIGHT_ARROW',
  LEFT_ARROW: 'JSED__LEFT_ARROW',
  REVEAL: 'JSED__REVEAL',
  // editing
  ENTER: 'JSED__ENTER',
  DELETE: 'JSED__DELETE',
  // selection
  EXTEND_RIGHT_ARROW: 'JSED__EXTEND_RIGHT_ARROW',
  EXTEND_LEFT_ARROW: 'JSED__EXTEND_LEFT_ARROW',
  // undo
  UNDO: 'JSED__UNDO',
  REDO: 'JSED__REDO',
  EXTEND_NEXT: 'JSED__EXTEND_NEXT',
  EXTEND_PREVIOUS: 'JSED__EXTEND_PREVIOUS',
  WRAP_SELECTION: 'JSED__WRAP_SELECTION',
  // copy paste
  CUT: 'JSED__CUT',
  COPY: 'JSED__COPY',
  COPY_EMPTY_PREVIOUS: 'JSED__COPY_EMPTY_PREVIOUS',
  COPY_EMPTY_NEXT: 'JSED__COPY_EMPTY_NEXT',
  PASTE_BEFORE: 'JSED__PASTE_BEFORE',
  PASTE_AFTER: 'JSED__PASTE_AFTER',
  PASTE_APPEND: 'JSED__PASTE_APPEND',
  // focus ops
  DELETE_FOCUSED_ELEMENT: 'JSED__DELETE_FOCUSED_ELEMENT',
  UNWRAP_FOCUS: 'JSED__UNWRAP_FOCUS',
  CONVERT_FOCUS: 'JSED__CONVERT_FOCUS',
  INSERT_ELEMENT_AFTER_FOCUS: 'JSED__INSERT_ELEMENT_AFTER_FOCUS',
  INSERT_ELEMENT_BEFORE_FOCUS: 'JSED__INSERT_ELEMENT_BEFORE_FOCUS',
  APPEND_NEW_ELEMENT_IN_FOCUS: 'JSED__APPEND_NEW_ELEMENT_IN_FOCUS',
  INSERT_SPACE_BEFORE_FOCUS: 'JSED__INSERT_SPACE_BEFORE_FOCUS',
  REMOVE_SPACE_BEFORE_FOCUS: 'JSED__REMOVE_SPACE_BEFORE_FOCUS',
  INSERT_SPACE_AFTER_FOCUS: 'JSED__INSERT_SPACE_AFTER_FOCUS',
  REMOVE_SPACE_AFTER_FOCUS: 'JSED__REMOVE_SPACE_AFTER_FOCUS',
  INSERT_ANCHOR_IN_FOCUS: 'JSED__INSERT_ANCHOR_IN_FOCUS',
  INSERT_ANCHOR_BEFORE_FOCUS: 'JSED__INSERT_ANCHOR_BEFORE_FOCUS',
  REMOVE_ANCHOR_BEFORE_FOCUS: 'JSED__REMOVE_ANCHOR_BEFORE_FOCUS',
  INSERT_ANCHOR_AFTER_FOCUS: 'JSED__INSERT_ANCHOR_AFTER_FOCUS',
  REMOVE_ANCHOR_AFTER_FOCUS: 'JSED__REMOVE_ANCHOR_AFTER_FOCUS',
  // cursor ops
  INSERT_SPACE_AFTER_CURSOR: 'JSED__INSERT_SPACE_AFTER_CURSOR',
  REMOVE_SPACE_AFTER_CURSOR: 'JSED__REMOVE_SPACE_AFTER_CURSOR',
  INSERT_SPACE_BEFORE_CURSOR: 'JSED__INSERT_SPACE_BEFORE_CURSOR',
  REMOVE_SPACE_BEFORE_CURSOR: 'JSED__REMOVE_SPACE_BEFORE_CURSOR',
  // misc
  ENABLE_LEGACY_ELEMENT_INDICATOR: 'JSED__ENABLE_LEGACY_ELEMENT_INDICATOR',
  ENABLE_ELEMENT_INDICATOR: 'JSED__ENABLE_ELEMENT_INDICATOR'
} as const;

export type JsedActionId = (typeof JsedCommand)[keyof typeof JsedCommand];
