export { JsedDocument } from './JsedDocument.js';

/**
 * The focus has been set.
 *
 * The target could be an FOCUSABLE or a TOKEN.
 */
export type JsedFocusEvent = JsedFocusEventBase<'FOCUS'>;
/**
 * The focus wants to be set to the target.
 *
 * The receiver of this event can accept or reject the focus request.
 * If accepted, this will generate a JsedFocusEvent.
 */
export type JsedFocusRequestEvent = JsedFocusEventBase<'FOCUS_REQUEST'>;

/**
 * Events that are emitted due to navigation and selection of FOCUSABLE's within the document (aka the FOCUS action).
 *
 * The listener to this event will decide if the FOCUSABLE should become the active FOCUS based on this event.
 */
type JsedFocusEventBase<T> =
  | {
      type: T;
      targetType: 'FOCUSABLE';
      element: HTMLElement;
    }
  | {
      type: T;
      targetType: 'TOKEN';
      /**
       * The TOKEN (usually a span element).
       */
      token: HTMLElement;
      /**
       * The string value of the TOKEN .
       */
      value: string;
    };

/**
 * Events generated by a TokenCursor instance.
 */
export type TokenCursorEvent = {
  type: 'CHANGE';
  value: string;
};
