import type { DocumentAction } from './lib/document-action';

export type JsedDocument = {
  /**
   * The root node of the subtree of the DOM that is potentially editable.
   */
  root: HTMLElement;
  /**
   * The document of the root.  This is a convenience, because we can calculate
   * it at any time.
   */
  document: Document;
  window: Window;
  /**
   * The focused element (may be none).  Should not be a TOKEN .
   */
  active: HTMLElement | null;
  /**
   * The currently selected TOKEN (may be none).
   */
  activeToken: HTMLElement | null;
  /**
   * Handles showCurrentSiblings.
   */
  SIB_HIGHLIGHT: Set<HTMLElement>;
  /**
   * Track which elements have been tokenized.  Such elements must have text
   * nodes as direct descendents.
   */
  tokenized: WeakMap<HTMLElement, boolean>;
  actions: DocumentAction;
  listeners: {
    /**
     * Register a listener for FOCUS events.  Consumer can decide if the FOCUS event should occur.
     */
    FOCUS: null | ((evt: JsedFocusEvent) => boolean);
    /**
     * Register a listener for TOKEN_FOCUS events.  Consumer can decide if the TOKEN_FOCUS event should occur.
     */
    TOKEN_FOCUS: null | ((evt: JsedTokenFocusEvent) => boolean);
  };
  unload: () => void;
  /**
   * Request a cursor for the current token.
   */
  requestCursor: (params: {
    token: HTMLElement;
    ceiling: HTMLElement | null;
  }) => IJsedCursor;
};

/**
 * Events that are emitted due to navigation and selection of TOKEN's within the document (aka the TOKEN_FOCUS action).
 * 
 * The listener to this event will decide if the TOKEN in this event should become the active token based on this event.
 */
export type JsedTokenFocusEvent = {
  type: 'FOCUS';
  targetType: 'TOKEN';
  /**
   * The TOKEN (usually a span element).
   */
  token: HTMLElement;
  /**
   * The string value of the TOKEN .
   */
  value: string;
  /**
   * The focused TOKEN is a new token but it has replaced the previously focused token.
   */
  replaced: boolean;
  /**
   * True if `token` is on a different line to the currently active `token`.  If there is no previously active token, return true.
   *
   * A line is defined as LINE (see DEFINITIONS.md) .
   *
   * This flag also supports TOKEN_FOCUS_PARENT_ONLY which allows us to focus on an F_ELEM on the first click/touch rather than focusing on a token.
   */
  lineChange: boolean;
};

/**
 * Events that are emitted due to navigation and selection of F_ELEM's within the document (aka the FOCUS action).
 *
 * The listener to this event will decide if the F_ELEM should become the active FOCUS based on this event.
 */
export type JsedFocusEvent = {
  type: 'FOCUS';
  targetType: 'F_ELEM';
};

export type IJsedCursor = {
  /**
   * Return the active TOKEN that the cursor is on.
   */
  getToken: () => HTMLElement;
  /**
   * Move to previous token if it exists.
   */
  movePrevious: () => void;
  /**
   * Move to next token if it exists.
   */
  moveNext: () => void;
  /**
   * Replace the value of the current token with a new value.
   */
  replace: (val: string) => void;
  /**
   * Delete the current token.
   */
  delete: () => void; // go back to previous word or next if no previous
  /**
   * Append a new token after the current one.
   */
  append: (val: string) => HTMLElement;
  /**
   * Prepend a new token after the current one.
   */
  prepend: () => void;
  /**
   * Request the cursor do a new focus.
   *
   * Normally this is to do a TOKEN_FOCUS on another token under the same F_ELEM eg created as a result of calling `append`.
   */
  focus: (el: HTMLElement) => boolean;
  /**
   * Close the current edit session.
   */
  close: () => void;
};

/**
 * Events generated by a JsedCursor instance.
 */
export type JsedCursorEvent = {
  type: 'CHANGE';
  value: string;
};
