import type { Navigator } from './lib/navigator';

export type JsedDocument = {
  /**
   * The root node of the subtree of the DOM that is potentially editable.
   */
  root: HTMLElement;
  /**
   * The document of the root.  This is a convenience, because we can calculate
   * it at any time.
   */
  document: Document;
  window: Window;
  /**
   * The currently selected TOKEN (may be none).
   */
  // activeToken: HTMLElement | null;
  /**
   * Handles showCurrentSiblings.
   */
  SIB_HIGHLIGHT: Set<HTMLElement>;
  actions: Navigator;
  listeners: {
    /**
     * Register a listener for FOCUS events.  Consumer can decide if the FOCUS event should occur.
     */
    FOCUS: null | ((evt: JsedFocusEvent) => boolean);
  };
  unload: () => void;
  /**
   * Request a cursor for the current token.
   */
  requestCursor: (params: {
    token: HTMLElement;
    ceiling: HTMLElement | null;
  }) => IJsedCursor;
};

/**
 * Events that are emitted due to navigation and selection of TOKEN's within the document (aka the TOKEN_FOCUS action).
 *
 * The listener to this event will decide if the TOKEN in this event should become the active token based on this event.
 */
/**
 * Events that are emitted due to navigation and selection of F_ELEM's within the document (aka the FOCUS action).
 *
 * The listener to this event will decide if the F_ELEM should become the active FOCUS based on this event.
 */
export type JsedFocusEvent =
  | {
      type: 'FOCUS';
      targetType: 'F_ELEM';
    }
  | {
      type: 'FOCUS';
      targetType: 'TOKEN';
      /**
       * The TOKEN (usually a span element).
       */
      token: HTMLElement;
      /**
       * The string value of the TOKEN .
       */
      value: string;
    };

export type IJsedCursor = {
  setToken: (token: HTMLElement) => void;
  /**
   * Return the active TOKEN that the cursor is on.
   */
  getToken: () => HTMLElement;
  /**
   * Move to previous token if it exists.
   */
  movePrevious: () => void;
  /**
   * Move to next token if it exists.
   */
  moveNext: () => void;
  /**
   * Replace the value of the current token with a new value.
   */
  replace: (val: string) => void;
  /**
   * Delete the current token.
   */
  delete: () => void; // go back to previous word or next if no previous
  /**
   * Append a new token after the current one.
   */
  append: (val: string) => HTMLElement;
  /**
   * Prepend a new token after the current one.
   */
  prepend: () => void;
  /**
   * Request the cursor do a new focus.
   *
   * Normally this is to do a TOKEN_FOCUS on another token under the same F_ELEM eg created as a result of calling `append`.
   */
  focus: (el: HTMLElement) => boolean;
  /**
   * Close the current edit session.
   */
  close: () => void;
};

/**
 * Events generated by a JsedCursor instance.
 */
export type JsedCursorEvent = {
  type: 'CHANGE';
  value: string;
};
