/**
 * What can be edited and focused on.
 */

import { JSED_DOM_ROOT_ID, JSED_IGNORE_CLASS } from './constants.js';
import { isToken } from './token.js';

const FORM_FOCUSABLE = [
  'input',
  'select',
  'textarea',
  'button',
  'optgroup',
  'option',
  'fieldset',
  'label'
];

/**
 * Detect a subclass of IGNORABLE's that are natively focusable elements.
 *
 * This was probably more important when FOCUS relied on messing with native
 * focus eg tabindex.
 *
 * @deprecated
 */
export function isAlreadyFocusable(el: Element): boolean {
  if (FORM_FOCUSABLE.indexOf(el.tagName.toLowerCase()) !== -1) {
    return true;
  }
  if (el.hasAttribute('contenteditable') && el.getAttribute('contenteditable') === 'true') {
    return true;
  }
  if (el.getAttribute('tabindex')) {
    return true;
  }
  return false;
}

/**
 * Detect ISLAND's.
 *
 * This can be used to FOCUS on things that may require special treatment such
 * as a katex element that has been generated by katex.
 */
export function isIsland(el: Element | Node | null | undefined): boolean {
  if (el instanceof Element) {
    if (el.classList.contains('katex')) {
      return true;
    }
    if (el.id === JSED_DOM_ROOT_ID) {
      return true;
    }
  }
  return false;
}

/**
 * Detect IGNORABLE's.
 *
 * An example might be an element indicator that floats next to the element and
 * shows its tag name.  The indicator is a visual aid and not a part of the
 * document.
 */
export function isIgnorable(el: Element): boolean {
  if (el.classList.contains(JSED_IGNORE_CLASS)) {
    return true;
  }
  return false;
}

/**
 * Test if the element is an FOCUSABLE.
 */
export function isFocusable(el: EventTarget | Element | null | undefined): el is HTMLElement {
  if (el instanceof window.HTMLScriptElement) {
    return false;
  }
  const isHTMLElement = el instanceof window.HTMLElement;
  if (isHTMLElement) {
    if (el?.id === JSED_DOM_ROOT_ID) {
      return false;
    }
    // Tokens (text) get a cursor and are not treated as focusable.
    if (isToken(el)) {
      return false;
    }
    if (isIgnorable(el)) {
      return false;
    }
  }
  return isHTMLElement;
}
