/**
 * Element classification predicates for the FOCUSABLE taxonomy.
 *
 * Primitives (`isFocusable`, `isIsland`, `isInlineFlow`, `isToken`, etc.) are
 * independent checks that each answer one question. Derived predicates
 *
 * See docs/vocabulary.md for the full taxonomy.
 */

import {
  JSED_IMPLICIT_CLASS,
  JSED_ANCHOR_CLASS,
  JSED_TOKEN_CLASS,
  JSED_APP_ROOT_ID,
  JSED_IGNORE_CLASS,
  JSED_CURSOR_TRANSPARENT_CLASS
} from './constants.js';

// ============================================================================
// Primitives
// ============================================================================

const FORM_FOCUSABLE = [
  'input',
  'select',
  'textarea',
  'button',
  'optgroup',
  'option',
  'fieldset',
  'label'
];

/**
 * Detect a subclass of IGNORABLE's that are natively focusable elements.
 *
 * This was probably more important when FOCUS relied on messing with native
 * focus eg tabindex.
 *
 * @deprecated
 */
export function isAlreadyFocusable(el: Element): boolean {
  if (FORM_FOCUSABLE.indexOf(el.tagName.toLowerCase()) !== -1) {
    return true;
  }
  if (el.hasAttribute('contenteditable') && el.getAttribute('contenteditable') === 'true') {
    return true;
  }
  if (el.getAttribute('tabindex')) {
    return true;
  }
  return false;
}

/**
 * Detect IGNORABLE's.
 *
 * An example might be an element indicator that floats next to the element and
 * shows its tag name.  The indicator is a visual aid and not a part of the
 * document.
 */
export function isIgnorable(el: Element): boolean {
  if (el.classList.contains(JSED_IGNORE_CLASS)) {
    return true;
  }
  return false;
}

/**
 * Detect if the element is a TOKEN .
 */
export function isToken(el: Node | null | undefined): boolean {
  const isHTMLElement = el instanceof window.HTMLElement;
  if (isHTMLElement) {
    return el.classList.contains(JSED_TOKEN_CLASS);
  }
  return false;
}

export function isAnchor(el: HTMLElement): boolean {
  return isToken(el) && el.classList.contains(JSED_ANCHOR_CLASS);
}

/**
 * Test if the element is an FOCUSABLE.
 */
export function isFocusable(el: EventTarget | Element | null | undefined): el is HTMLElement {
  if (el instanceof window.HTMLScriptElement) {
    return false;
  }
  const isHTMLElement = el instanceof window.HTMLElement;
  if (isHTMLElement) {
    if (el?.id === JSED_APP_ROOT_ID) {
      return false;
    }
    // Tokens (text) get a cursor and are not treated as focusable.
    if (isToken(el)) {
      return false;
    }
    if (isIgnorable(el)) {
      return false;
    }
  }
  return isHTMLElement;
}

/**
 * Detect ISLAND's.
 *
 * This can be used to FOCUS on things that may require special treatment such
 * as a katex element that has been generated by katex.
 */
export function isIsland(el: Node | null | undefined): boolean {
  if (el instanceof Element) {
    if (el.classList.contains('katex')) {
      return true;
    }
    if (el.id === JSED_APP_ROOT_ID) {
      return true;
    }
  }
  return false;
}

/**
 * Pure display predicate: does this element have inline-flow display?
 *
 * Returns true when the element's computed display is `inline` or `inline flow`
 * AND the element is not floated (floated elements are pulled out of normal flow).
 *
 * This is a primitive — no FOCUSABLE, ISLAND, or class checks. Use it when you
 * need just the CSS display-model answer. Callers combine it with other primitives
 * to derive taxonomy labels (e.g. INLINE_FLOW = `isFocusable && isInlineFlow && !isIsland
 * && !isImplicitLine`).
 */
export function isInlineFlow(el: Node | null): boolean {
  if (!isFocusable(el)) return false;
  const styles = window.getComputedStyle(el);
  if (!['none', ''].includes(styles.float)) return false;
  if (styles.display === 'inline') return true;
  if (styles.display === 'inline flow') return true;
  return false;
}

/**
 * Detect IMPLICIT_LINE .
 */
export function isImplicitLine(node: Node) {
  return isFocusable(node) && node.classList.contains(JSED_IMPLICIT_CLASS);
}

/**
 * Detect TRANSPARENT_BLOCK .
 */
export function isTransparentBlock(node: Node | null): boolean {
  return isFocusable(node) && node.classList.contains(JSED_CURSOR_TRANSPARENT_CLASS);
}

// ============================================================================
// Derived
// ============================================================================

/**
 * Detect LINE.
 */
export function isLine(el: Node | null): boolean {
  if (!el) return false;
  if (!isFocusable(el)) return false;
  if (isTransparentBlock(el)) return false;
  if (isToken(el)) return false;
  if (isImplicitLine(el)) return false;
  if (isInlineFlow(el)) return false;
  if (isIsland(el)) return false;
  return true;
}

/** Visit predicate for LINE_SIBLING traversal: TOKEN's, ISLAND's, and OPAQUE_BLOCK's. */
export function isLineSibling(el: Node): boolean {
  if (isToken(el) || isIsland(el)) {
    return true;
  }
  return isFocusable(el) && !isCursorTransparent(el);
}

/** Descend predicate for LINE_SIBLING traversal. */
export function isCursorTransparent(n: Node): boolean {
  if (!isFocusable(n)) return false;
  if (isIsland(n)) return false;
  if (isInlineFlow(n)) return true;
  if (isTransparentBlock(n)) return true;
  if (isImplicitLine(n)) return true;
  return false;
}
