/**
 * Element classification and traversal predicates.
 *
 * Identity predicates (`is*`), sibling helpers, LINE_SIBLING traversal,
 * and LINE detection. This module sits beneath token.ts — token.ts imports
 * from here, never the reverse.
 */

import {
  JSED_IMPLICIT_CLASS,
  JSED_ANCHOR_CLASS,
  JSED_TOKEN_CLASS,
  JSED_APP_ROOT_ID,
  JSED_IGNORE_CLASS,
  JSED_CURSOR_OPAQUE_CLASS
} from './constants.js';
import { findNextNode, findPreviousNode } from './walk2.js';

// #region Identity predicates

const FORM_FOCUSABLE = [
  'input',
  'select',
  'textarea',
  'button',
  'optgroup',
  'option',
  'fieldset',
  'label'
];

/**
 * Detect a subclass of IGNORABLE's that are natively focusable elements.
 *
 * This was probably more important when FOCUS relied on messing with native
 * focus eg tabindex.
 *
 * @deprecated
 */
export function isAlreadyFocusable(el: Element): boolean {
  if (FORM_FOCUSABLE.indexOf(el.tagName.toLowerCase()) !== -1) {
    return true;
  }
  if (el.hasAttribute('contenteditable') && el.getAttribute('contenteditable') === 'true') {
    return true;
  }
  if (el.getAttribute('tabindex')) {
    return true;
  }
  return false;
}

/**
 * Detect ISLAND's.
 *
 * This can be used to FOCUS on things that may require special treatment such
 * as a katex element that has been generated by katex.
 */
export function isIsland(el: Element | Node | null | undefined): boolean {
  if (el instanceof Element) {
    if (el.classList.contains('katex')) {
      return true;
    }
    if (el.id === JSED_APP_ROOT_ID) {
      return true;
    }
  }
  return false;
}

/**
 * Detect IGNORABLE's.
 *
 * An example might be an element indicator that floats next to the element and
 * shows its tag name.  The indicator is a visual aid and not a part of the
 * document.
 */
export function isIgnorable(el: Element): boolean {
  if (el.classList.contains(JSED_IGNORE_CLASS)) {
    return true;
  }
  return false;
}

/**
 * Test if the element is an FOCUSABLE.
 */
export function isFocusable(el: EventTarget | Element | null | undefined): el is HTMLElement {
  if (el instanceof window.HTMLScriptElement) {
    return false;
  }
  const isHTMLElement = el instanceof window.HTMLElement;
  if (isHTMLElement) {
    if (el?.id === JSED_APP_ROOT_ID) {
      return false;
    }
    // Tokens (text) get a cursor and are not treated as focusable.
    if (isToken(el)) {
      return false;
    }
    if (isIgnorable(el)) {
      return false;
    }
  }
  return isHTMLElement;
}

/**
 * Detect if the element is a TOKEN .
 */
export function isToken(
  el: EventTarget | Element | Node | ChildNode | ParentNode | null | undefined
): boolean {
  const isHTMLElement = el instanceof window.HTMLElement;
  if (isHTMLElement) {
    return el.classList.contains(JSED_TOKEN_CLASS);
  }
  return false;
}

export function isAnchor(el: HTMLElement): boolean {
  return isToken(el) && el.classList.contains(JSED_ANCHOR_CLASS);
}

/**
 * Detect INLINE — a FOCUSABLE that acts as inline markup (e.g. `<em>`, `<a>`).
 * The CURSOR traverses seamlessly through INLINE's to visit their TOKEN's.
 */
export function isInline(el: Node | ChildNode | ParentNode | null): boolean {
  if (!el) return false;
  if (!isFocusable(el)) return false;
  if (isIsland(el)) return false;

  // This is an implicit line, it may be inline, but we treat it like a separate LINE.
  if (el.classList.contains(JSED_IMPLICIT_CLASS)) return false;

  const styles = window.getComputedStyle(el);
  if (!['none', ''].includes(styles.float)) {
    return false;
  }
  if (styles.display === 'inline') return true;
  if (styles.display === 'inline flow') return true;
  return false;
}

/**
 * Detect LINE — a FOCUSABLE that is not a TOKEN, INLINE, or ISLAND.
 * Examples: `<div>`, `<p>`, `<h1>`, inline-block `<span>`.
 */
export function isLine(el: Node | ChildNode | ParentNode | null): boolean {
  if (!el) return false;
  if (!isFocusable(el)) return false;
  if (isToken(el)) return false;
  if (isInline(el)) return false;
  if (isIsland(el)) return false;
  return true;
}

/**
 * Detect OPAQUE_BLOCK — a FOCUSABLE explicitly marked so FOCUS can descend
 * but the CURSOR treats it as opaque (visit=yes, descend=no).
 */
export function isCursorBoundary(el: Node | ChildNode | ParentNode | null): boolean {
  if (!el || !(el instanceof Element)) return false;
  return el.classList.contains(JSED_CURSOR_OPAQUE_CLASS);
}

/**
 * Detect TRANSPARENT_BLOCK — the default for any non-INLINE, non-ISLAND FOCUSABLE
 * that is not a OPAQUE_BLOCK. The CURSOR descends into it seamlessly (like INLINE).
 */
export function isBlockTransparent(el: Node | ChildNode | ParentNode | null): boolean {
  return isLine(el) && !isCursorBoundary(el);
}

export function isImplicitLine(node: Node): boolean {
  return (
    node.nodeType === Node.ELEMENT_NODE &&
    (node as HTMLElement).className.includes(JSED_IMPLICIT_CLASS)
  );
}

/** Visit predicate for LINE_SIBLING traversal: TOKEN's and ISLAND's. */
export function isLineSibling(el: ParentNode | ChildNode): boolean {
  return isToken(el) || isIsland(el) || isCursorBoundary(el);
}

// #endregion

// #region Sibling helpers

/**
 * Get previous visible (non-IGNORABLE) element sibling.
 * Walks backwards skipping IGNORABLE's. Returns null if none found.
 */
export function getPreviousVisibleSibling(el: HTMLElement | ChildNode): HTMLElement | null {
  let prev = (el as HTMLElement).previousElementSibling;
  while (prev && isIgnorable(prev)) {
    prev = prev.previousElementSibling;
  }
  return (prev as HTMLElement) ?? null;
}

/**
 * Get next visible (non-IGNORABLE) element sibling.
 * Walks forward skipping IGNORABLE's. Returns null if none found.
 */
export function getNextVisibleSibling(el: HTMLElement | ChildNode): HTMLElement | null {
  let next = (el as HTMLElement).nextElementSibling as HTMLElement | null;
  while (next && isIgnorable(next)) {
    next = next.nextElementSibling as HTMLElement | null;
  }
  return next ?? null;
}

/**
 * Get the previous TOKEN SIBLING if there is one.  Siblings must be contiguous text tokens with NO intervening tags including inline tags.
 *
 * `el` may or may not be a TOKEN .  `el` might be an inline tag eg an em-tag.
 *
 * This is basically a souped up version of the DOM's
 * node.previousElementSibling.  We may need to handle undo and other weird
 * stuff, so we use a wrapper here.
 */
export function getPreviousTokenSibling(el: HTMLElement): HTMLElement | null {
  const prev = getPreviousVisibleSibling(el);
  if (isToken(prev)) {
    return prev;
  }
  return null;
}

/**
 * Similar to getPreviousTokenSibling but for the next SIBLING.
 */
export function getNextTokenSibling(el: HTMLElement): HTMLElement | null {
  const next = getNextVisibleSibling(el);
  if (isToken(next)) {
    return next;
  }
  return null;
}

// #endregion

// #region LINE detection and LINE_SIBLING traversal

/**
 * Find the LINE associated with `el`. Returns `el` itself if it is a LINE.
 *
 * Used by FOCUS-level code (Nav). CURSOR-level code should use an explicitly
 * stored LINE rather than calling this per-hop.
 */
export function getLine(el: ChildNode): HTMLElement {
  if (!el) {
    throw new Error(`getLine: element is null`);
  }
  for (let p: ParentNode | ChildNode | null = el; ; p = p?.parentNode) {
    if (!p) {
      throw new Error(`getLine: expected parentNode to exist`);
    }
    if (isLine(p)) {
      return p as HTMLElement;
    }
  }
  throw new Error(`getLine: end of for-loop`);
}

export function isSameLine(tok1: HTMLElement, tok2: HTMLElement): boolean {
  const line1 = getLine(tok1);
  const line2 = getLine(tok2);
  return line1 === line2;
}

/** Options for LINE_SIBLING traversal functions. */
export type LineSiblingOptions = {
  /** Called before descending into a TRANSPARENT_BLOCK. Use for lazy tokenization. */
  onEnterBlockTransparent?: (el: HTMLElement) => void;
};

/** Build the descend predicate for LINE_SIBLING traversal. */
function lineSiblingDescend(options?: LineSiblingOptions): (n: ParentNode | ChildNode) => boolean {
  return (n) => {
    if (isInline(n)) return true;
    if (isBlockTransparent(n)) {
      options?.onEnterBlockTransparent?.(n as HTMLElement);
      return true;
    }
    return false;
  };
}

/**
 * Get previous LINE_SIBLING within `line`.
 */
export function getPreviousLineSibling(el: HTMLElement, line: HTMLElement, options?: LineSiblingOptions): HTMLElement | null {
  for (const prev of findPreviousNode(el, line, {
    visit: isLineSibling,
    descend: lineSiblingDescend(options)
  })) {
    return prev as HTMLElement;
  }
  return null;
}

/**
 * Get next LINE_SIBLING within `line`.
 */
export function getNextLineSibling(el: HTMLElement, line: HTMLElement, options?: LineSiblingOptions): HTMLElement | null {
  for (const next of findNextNode(el, line, {
    visit: isLineSibling,
    descend: lineSiblingDescend(options)
  })) {
    return next as HTMLElement;
  }
  return null;
}

/**
 * Get the first LINE_SIBLING in a LINE — may be a TOKEN or an ISLAND.
 */
export function getFirstLineSibling(line: HTMLElement, options?: LineSiblingOptions): HTMLElement | null {
  const descendFn = lineSiblingDescend(options);
  for (const node of findNextNode(line, line, {
    visit: isLineSibling,
    descend: (n) => n === line || descendFn(n)
  })) {
    return node as HTMLElement;
  }
  return null;
}

// #endregion
